### PR TITLE
Added: caching lookup list on basis function ID

### PR DESCRIPTION
**Pull request by VikingScientist**
As requested.

It seems that `LRSpline::getBasisfunction(int)` is called more than predicted and  as such  it only makes sense to cache these values for quick lookup and repeated calls to this function.

Note that this PR is lacking an accompanying regression test so I'd advised to test it (maybe run the entire IFEM test suite) before accepting the PR.

### CODE REVIEW

**Review by akva2 — APPROVED** [review]
This mandates the cache but I think that's fine.

**Comment by VikingScientist** [comment]
> This mandates the cache but I think that's fine.

What mandates the cache? I don't get it...

**Comment by akva2** [comment]
you will always generate the cache if getBasisFunction is called, while in my variant it would fallback to the old code.

**Comment by akva2** [comment]
i have tested in ifem. all tests pass and the multipatch adaptive ones (particular 3D) runs quite a lot faster. it's all good . i think this is good. bump version please so we can make a release.

**Pull request merged**
